name:               "humb1ec0ding"
description:        "Writeup oriented CTF"

url:                "https://humb1ec0ding.github.io "
author:             "humb1ec0ding"
email:              "humblecoding@gmail.com"

gravatar_hash:      "e32341f112e5bde5311a0a8874837dcc"
github:             "humb1ec0ding"

disqus_shortname:   "humb1ec0ding"

background:         "https://unsplash.it/2000/1200?image=992"

paginate:           10
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate